### ISSUE TITLE
在使用了sdlv以后，通过后台统计出现这个崩溃

### ISSUE THREAD

**Issue by bxjxxyy** [yydcdut/SlideAndDragListView#35]
我的Activity里面的XML将SlideAndDragListView的id设置为了android:id="@+id/step_list"。XML中没有其他重复id。
在开发时没有遇到问题，发布后通过统计发现了如下崩溃信息。崩溃率大概0.05%。
能否帮忙分析一下原因？自己分析不出来了。
java.lang.RuntimeException: Unable to start activity  ComponentInfo{com.myapp/com.myapp.myactivity}:
 java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.AbsListView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/step_list. Make sure other views do not use the same id.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.AbsListView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/step_list. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:13827)
	at android.view.View.dispatchRestoreInstanceState(View.java:13803)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2917)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2923)
	at android.view.View.restoreHierarchyState(View.java:13781)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2099)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1046)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1001)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1171)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
	... 10 more

**Comment by yydcdut** [comment]
额，我大概知道原因了，谢谢！，我这几天就修复

**Comment by bxjxxyy** [comment]
能说下是什么原因么？自己是没看明白

**Comment by yydcdut** [comment]
`WrapperAdapter` 里面里面有两个常量，目的是设置id，可能是这里的问题
诶，但是不确定最终是不是这里的问题，只是说觉得这里可能会出现问题

**Comment by bxjxxyy** [comment]
现在直接使用0.7.0版本的可以么？是修复了这个问题的么？还是用 [fix](https://github.com/yydcdut/SlideAndDragListView/commit/7df9670d5c2b0851ca6791530ea21fae1c37eda6) 的呢

**Comment by yydcdut** [comment]
修复了，0.7.0就可以直接用
但是不能确保出错的地方就是那里，只是说那个地方可能会导致错误
可以先换上0.7.0然后再观察观察，哈哈

**Comment by bxjxxyy** [comment]
0.7.0还是存在个别机型有那个错误。根据百度统计，有OPPO R9（电信版）Android 5.1，oppo N1 mini  Android 4.3，一加A0001 Android 6.0，vivo x7plus Android 5.1等

**Comment by yydcdut** [comment]
那可能不是库的问题了，库里面没有对于id方面的操作了

**Comment by bxjxxyy** [comment]
我也是很纳闷。错误里面说的This view's id is id/step_list. Make sure other views do not use the same id.
step_list这个id就是我给SlideAndDragListView设置的id。
