### ISSUE TITLE
Observer com.yydcdut.sdlv.WrapperAdapter$1@2a68a57 was not registered.

### ISSUE THREAD

**Issue by mywitness** [yydcdut/SlideAndDragListView#44]
嵌在ViewPager中，当滑动时可能造成如题错误，如果不用该控件现有BaseAdapter是没有问题的。具体如下：
java.lang.IllegalStateException: Observer com.yydcdut.sdlv.WrapperAdapter$1@2a68a57 was not registered.
                                                                                  at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                                  at android.widget.BaseAdapter.unregisterDataSetObserver(BaseAdapter.java:42)
                                                                                  at com.yydcdut.sdlv.WrapperAdapter.removeDataSetObserver(WrapperAdapter.java:308)
                                                                                  at com.yydcdut.sdlv.SlideListView.onDetachedFromWindow(SlideListView.java:481)
                                                                                  at android.view.View.dispatchDetachedFromWindow(View.java:15471)
                                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3226)
                                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3218)
                                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3218)
                                                                                  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4754)
                                                                                  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4728)
                                                                                  at android.view.ViewGroup.removeView(ViewGroup.java:4659)
                                                                                  at android.support.v4.view.ViewPager.removeView(ViewPager.java:1527)

请问这个问题是不兼容的API版本造成的，还是Adapter写的有问题？有什么办法可以避免观察者导致的问题？目前给ViewPager设置缓存数量确保不刷新时才不会出问题

**Comment by yydcdut** [comment]
有个pr应该解决了这个问题，可以试试0.7.1
